services:
  app:
    build: .
    container_name: mama-notifier-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: always
