name: mama_notifier_app
description: App móvil para Mama-Notifier con monitoreo Wi-Fi y envío automático de eventos.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  connectivity_plus: ^7.1.1
  network_info_plus: ^8.1.0
  flutter_secure_storage: ^10.3.1
  workmanager: ^0.9.0+3
  uuid: ^4.5.3
  flutter_foreground_task: ^9.2.2
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
